package exceptions_1;

public class E4 {

    //    Bilgi: ArrayIndexOutOfBoundsException class'i Exception class'in child class'idir.


 //   public static void main(String[] args) {
//
//    try {
//                int a[]= {7, 8, 9};
//                for (int i = 1; i <= 3; i++){
//                    System.out.println(a[i]);
//                }
//            } catch(Exception e) {
//                System.out.println ("Exception");
//            }catch(ArrayIndexOutOfBoundsException e) {
//                System.out.println ("Out of index");
//            }finally {
//                System.out.println("Done!");
//            }
//        }

//        Compile time error verir


//    public static void main(String[] args) {
//
//    try {
//                int a[]= {7, 8, 9};
//                for (int i = 1; i <= 2; i++){
//                    System.out.println(a[i]);
//                }
//            }catch(ArrayIndexOutOfBoundsException e) {
//                System.out.println ("Out of index");
//            }finally {
//                System.out.println("Done!");
//            }
//        }

//    Output
//        8
//        9
//    Done!


//    public static void main(String[] args) {
//
//    try {
//                int a[]= {7, 8, 9};
//                for (int i = 1; i <= 7; i++){
//                    System.out.println(a[i]);
//                }
//            }catch(Exception e) {
//                System.out.println ("Exception");
//            }finally {
//                System.out.println("Done!");
//            }
//        }

//    Output
//        8
//        9
//   Exception
//   Done!



}

